apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-pred
  labels:
    app: brain-pred
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-pred
  template:
    metadata:
      labels:
        app: brain-pred
    spec:
      containers:
      - name: brainpred-mlops
        image: 848770179812.dkr.ecr.us-east-1.amazonaws.com/venkatesh-mlops:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: brain-pred-service
spec:
  selector:
    app: brain-pred
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer

